#!/usr/bin/env perl
use Mojolicious::Lite;

use lib map { "$ENV{HOME}/sandbox/$_/lib" } qw(EncodedColumn-Bcrypt);
use lib 'lib';
use AuthEg::DB::Plugin;

my ($name, $pass) = @ARGV;

die "No user password provided!\n" unless $name && $pass;

plugin 'AuthEg::DB::Plugin';

my $result = app->add($name, $pass);
die "Can't create user!\n" unless $result;
print "User: $name created\n";
