#!/usr/bin/env perl

use strict;
use warnings;

use lib map { "$ENV{HOME}/sandbox/$_/lib" } qw(EncodedColumn-Bcrypt);

use Mojo::File qw(curfile);
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;

Mojolicious::Commands->start_app('AuthEg');
