#!/usr/bin/env perl

use lib 'lib';
use AuthEg::DB::Schema;

use Mojolicious::Lite;

my ($name, $pass) = @ARGV;

die "No user password provided!\n" unless $name && $pass;

my $schema = AuthEg::DB::Schema->connect('db');

my $rs = $schema->resultset('Account')->search({ name => $name });

while (my $acct = $rs->next) {
  if ($acct->name eq $name) {
    my $x = $acct->check_password($pass) ? 1 : 0;
warn __PACKAGE__,' L',__LINE__,' ',,"$name PASS? $x\n";
  }
}
